project:
  type: website

website:
  title: "Applied & Computational Mathematics Seminar"
  favicon: graphics/mLogo.gif
  navbar:
    foreground: "#00693e"
    logo: graphics/mLogo.gif
    left:
      - href: index.qmd
      - past_seminars.qmd

format:
  html:
    theme: simplex
    css: styles.css
    page-layout: full
    toc: false



