---
title: "Broken Rays, Cones, and Stars in Tomography"
---
**Speaker:** [Gaik Ambartsoumian](https://gambarts.utasites.cloud/) (UT Arlington)

**Date:** 10/4/23

**Abstract:** Mathematical models of various imaging modalities are based on integral transforms mapping a function (representing the image) to its integrals along specific families of curves or surfaces. Those integrals are generated by external measurements of physical signals, which are sent into the imaging object, get modified as they pass through its medium and are captured by sensors after exiting the object. The mathematical task of image reconstruction is then equivalent to recovering the image function from the appropriate family of its integrals, i.e. inverting the corresponding integral transform (often called a generalized Radon transform). A classic example is computerized tomography (CT), where the measurements of reduced intensity of X-rays that have passed though the body correspond to the X-ray transform of the attenuation coefficient of the medium. Image reconstruction in CT is achieved through inversion of the X-ray transform. In this talk, we will discuss several novel imaging techniques using scattered particles, which lead to the study of generalized Radon transforms integrating along trajectories and surfaces containing a ``vertex''. The relevant applications include single-scattering X-ray tomography, single-scattering optical tomography, and Compton camera imaging. We will present recent results about injectivity, inversion, stability and other properties of the broken ray transform, conical Radon transform and the star transform.