---
title: "Topics in Differential Equations, Inverse Problems, and Optimal Control"
---
**Speaker:** [Mario Bencomo](https://csm.fresnostate.edu/math/faculty-staff/resident/mbencomo.html) (California State U, Fresno)

**Date:** 1/30/24

**Abstract:** This talk covers a body of research under the category of optimization problems with differential equations as constraints, a unifying framework for some inverse and optimal control problems. The talk will focus on challenges associated with discretizing and estimating seismic sources as multipoles and discrete adjoint computations for relaxation Runge-Kutta methods. Accurate representation and estimation of seismic sources is crucial to the accuracy of imaging algorithms in exploration seismology. In order to account for source anisotropy, we model seismic sources of point-support as multipoles, i.e., a finite series of derivatives of the spatial delta function. We present a method for discretizing multipole sources in a finite difference setting. The multipole source inverse problem results in a highly ill-conditioned linear least squares problem which presents a challenge for iterative solvers such as conjugate gradient (CG). We propose a preconditioner consisting of time differo-integral operators based on analytical solutions to the wave equation to accelerate CG iterations. Relaxation Runge-Kutta (RRK) methods reproduce a fully discrete conservation of entropy for entropy stable semi-discretizations of nonlinear conservation laws. In this talk, we derive the discrete adjoint of RRK schemes, which are applicable to discretize-then-optimize approaches for optimal control problems. Numerical experiments demonstrate the importance of appropriately treating the relaxation parameter when computing the discrete adjoint.