---
title: "Emergence of polarization in a sigmoidal bounded-confidence model of opinion dynamics"
---
**Speaker:** [Heather Zinn Brooks](https://sites.google.com/g.hmc.edu/hzinnbrooks?pli=1) (Harvey Mudd)

**Date:** 10/17/23

**Abstract:** We propose a nonlinear bounded-confidence model (BCM) of continuous time opinion dynamics on networks with both persuadable individuals and zealots. The model is parameterized by a scalar γ, which controls the steepness of a smooth influence function that encodes the relative weights that nodes place on the opinions of other nodes. When γ = 0, this influence function exactly recovers Taylor’s averaging model; when γ → ∞, the influence function converges to that of a modified Hegselmann–Krause (HK) BCM. Unlike the classical HK model, however, our sigmoidal bounded-confidence model (SBCM) is smooth for any finite γ. We show that the set of steady states of our SBCM is qualitatively similar to that of the Taylor model when γ is small and that the set of steady states approaches a subset of the set of steady states of a modified HK model as γ → ∞. For several special graph topologies, we give analytical descriptions of important features of the space of steady states. A notable result is a closed-form relationship between the stability of a polarized state and the graph topology in a simple model of echo chambers in social networks. Because the influence function of our BCM is smooth, we are able to study it with linear stability analysis, which is difficult to employ with the usual discontinuous influence functions in BCMs. This is joint work with Phil Chodrow and Mason Porter.