---
title: "Epidemic Disease Modeling, Contact Networks and Clustering on Social Networks"
---
**Speaker:** [Zeynep Ertem](https://www.binghamton.edu/labs/datart/) (Binghamton)

**Date:** 10/1/24

**Abstract:** The COVID-19 pandemic has highlighted the importance of effective surveillance and containment strategies in public health. In this study, we examined the impact of county-level mandates on COVID-19 cases pre-post to the availability of vaccinations. We also emphasize the need for a dynamic model of policy, as changes in population behavior, conditions, and vaccination levels can alter policy effectiveness. Dr. Ertem will be talking about several models on different machine learning techniques to address several real-life problems in public health management. Mainly, she will describe an operations research-based approach can help improve efficiency in public health decisions. She will describe a new forecasting algorithm that uses multiple data sources to timely and accurately predict epidemic diseases. She will talk about her hierarchical framework uses multi-linear regression to combine forecasts from multiple data sources and greedy optimization with forward-selection to sequentially choose the most predictive combinations of data sources. Clique relaxations are used in classical models of cohesive subgroups in social network analysis. Clustering coefficient was introduced more recently as a structural feature characterizing small-world networks. Noting that cohesive subgroups tend to have high clustering coefficients, here she will introduce a new clique relaxation, 𝛼-cluster, defined by enforcing a lower bound ̨ on the clustering coefficient in the corresponding induced subgraph. She considers two variations of the clustering coefficient, namely, the local and global clustering coefficient. She analyzes certain structural properties of 𝛼-clusters and she develops mathematical optimization models for determining 𝛼-clusters of the largest size in a network and apply these models to several real-life social networks. In addition, she develops a novel network clustering algorithm based on local 𝛼-cluster.