---
title: "Testing and estimation for sparsity-inducing power penalties"
---
**Speaker:** [Maryclare Griffin](https://maryclare.github.io/) (UMass Amherst)

**Date:** 2/13/24

**Abstract:** Many penalized maximum likelihood estimators correspond to posterior mode estimators under specific prior distributions. Appropriateness of a particular class of penalty functions can therefore be interpreted as the appropriateness of a prior for the parameters. For example, the appropriateness of a lasso penalty for regression coefficients depends on the extent to which the empirical distribution of the regression coefficients resembles a Laplace distribution. We give a testing procedure of whether or not a Laplace prior is appropriate and accordingly, whether or not using a lasso penalized estimate is appropriate. Via simulations, we show that this testing procedure achieves the desired level and has enough power to detect violations of the Laplace assumption when the numbers of observations and unknown regression coefficients are large. We then introduce an adaptive procedure that chooses a more appropriate prior and corresponding penalty from the class of exponential power priors when the null hypothesis is rejected. We show that this can improve estimation of the regression coefficients both when they are drawn from an exponential power distribution and when they are drawn from a spike-and-slab distribution. Last, this motivates an improved pathwise coordinate descent method for estimating regression coefficients assuming an exponential power prior, which corresponds to a power penalty. We introduce and demonstrate the utility of the corresponding new pathwise coordinate descent method.