---
title: "Kernel Smoothing Operators on Thick Open Domains"
---
**Speaker:** [Mohammad Javad Latifi Jebelli](https://math.dartmouth.edu/~mjebelli/) (Dartmouth, Mathematics)

**Date:** 1/9/24

**Abstract:** Given an appropriate kernel function, it is known that the convolution operator would converge to the identity operator as the scaling parameter goes to zero. In this talk, we discuss the approximation properties of the 'normalized' convolution operators on certain domains in Euclidean space. Despite the fact that normalization breaks the symmetry of the convolution operators, we show that a local Hardy-Littlewood inequality holds in L^p(X), where p>1 and X is a 'thick' domain in n-dimensional Euclidean space. Using this inequality, we establish pointwise and Lp(X) convergence for the family of convolution operators. We demonstrate the application of such smoothing operators to sea ice piecewise-continuous density, velocity, and stress fields from discrete element models of sea ice dynamics.