---
title: "Evolution in the presence of large (but finite) offspring fluctuations"
---
**Speaker:** [Ethan Levien](https://elevien.github.io/) (Dartmouth, Mathematics)

**Date:** 5/30/23

**Abstract:** Evolution is driven by a tension between two opposing forces: random fluctuations in the genetic composition of a population, known as genetic drift, and deterministic selection. Among models of genetic drift, the classical Wright-Fisher diffusion (WFD) reigns supreme. The success of the WFD can be attributed to universality: Much like the Gaussian emerges universally from sums of iid random variables with finite variance, the WFD emerges as a universal large population size limit from numerous population genetics models in which the variance in offspring numbers is finite. However, an onslaught of data from the microbial world has revealed the limitations of this model, motivating the study of evolution in the presence of power law offspring distributions with infinite variance. In this talk, I will present results concerning models of neutral evolution where the variance in offspring is finite, but large relative to the population size. In particular, I will consider offspring distributions with Weibull log tails (the lognormal being a special case) in a particular ``thermodynamic’’ limit. These offspring distributions are motivated by biology, where they appear in models of microbial pathogens, but also by a connection to statistical physics where they appear in the context of spin glasses with long range interactions. By leveraging results from the theory of spin glasses, I will describe a new class of limit models for genetic drift which generalize the -Flemming Viot process – a phenomenological model for neutral evolution with skewed offspring distributions. If time permits I will also discuss the statistical structure of genealogies emerging from these models, which are connected to the forward dynamics via stochastic duality. These genealogies have some surprising characteristics including the simultaneous merging of multiple ancestral lineages.