---
title: "Applied Geometric Measure Theory from DeepCurrents to Topological Defects"
---
**Speaker:** [David Palmer](https://people.csail.mit.edu/drp/) (MIT)

**Date:** 2/7/23

**Abstract:** Choosing the right representation of geometry can often simplify knotty computational problems and expose new opportunities. I will talk about some of our work devising computational representations of geometry inspired by geometric measure theory and, in particular, minimal currents. First, while neural implicit representations offer a flexible way to encode surfaces and learn families of surfaces in computer vision, most methods are unable to reconstruct surfaces with boundary curves. In DeepCurrents (joint work with Dima Smirnov, Stephanie Wang, Albert Chern, and Justin Solomon), we propose a new hybrid representation that parametrizes currents via neural implicit functions and solves a minimal surface problem. By modifying the ambient metric such that the target geometry is minimal, we can learn arbitrary surfaces and families of surfaces with boundary, providing a building block for larger-scale surface representations. A completely different application of currents is to the problem of computing line or nematic fields, cross fields, and their generalizations on surfaces. Such fields are important to applications in computer graphics and computational engineering, and they have recently shown up in models of biological morphogenesis. Singularities or topological defects are an essential feature of such fields. But singularities challenge classical field optimization methods, whose energies tend to diverge or depend on discretization in their presence. By reformulating field optimization in terms of minimal currents in circle bundles, we obtain a convex relaxation that treats singularities as first-class citizens and yields reliable optimization.