---
title: "Adaptive localization in nonlinear ensemble transport filtering"
---
**Speaker:** [Maximilian Ramgraber](https://www.maxramgraber.com/) (MIT)

**Date:** 5/16/23

**Abstract:** Most ensemble filtering algorithms today rely on one of two update strategies. The ensemble Kalman filter (EnKF) and its many variants are sample-efficient but remain fundamentally restricted to linear updates, which limits fidelity in strongly nonlinear or non-Gaussian settings. Particle filters, on the other hand, can realize arbitrarily nonlinear updates for non-Gaussian problems, but often require intractable ensemble sizes to forestall ensemble collapse. A promising alternative may be found in ensemble transport methods. Transport methods construct a map from an unknown, potentially non-Gaussian target distribution—represented only through an ensemble of particles—to a well-defined reference distribution, often a standard multivariate Gaussian distribution. Inverting this map permits sampling from the target’s conditional distributions. Leveraging this operation, it is possible to derive true nonlinear generalizations of the EnKF and its smoothing variants. In this construction, the complexity of the map’s parameterization is a critical choice. More complex maps may capture increasingly complex distributional features but risk unfavourable bias-variance trade-offs. In this presentation, we present an efficient map adaptation scheme which not only (1) identifies an optimal degree of map complexity, but also (2) reveals and exploits conditional independence, yielding an efficient form of adaptive localization. We demonstrate the performance of the resulting adaptive ensemble transport filter in a chaotic and nonlinear setting and discuss its implications for high-dimensional environmental systems.