---
title: "Variational quantum algorithm for numerical PDE solving"
---
**Speaker:** [Pete Rigas](https://scholar.google.com/citations?user=pjytF18AAAAJ&hl=en&oi=sra) (Cornell)

**Date:** 9/20/23

**Abstract:** Classical-quantum hybrid algorithms have recently garnered significant attention, which are characterized by combining quantum and classical computing protocols to obtain readout from quantum circuits of interest. Recent progress due to Lubasch et al in a 2019 paper provides readout for solutions to the Schrodinger and Inviscid Burgers equations, by making use of a new variational quantum algorithm (VQA) which determines the ground state of a cost function expressed with a superposition of expectation values and variational parameters. In the following, we analyze additional computational prospects in which the VQA can reliably produce solutions to other PDEs that are comparable to solutions that have been previously realized classically, which are characterized with noiseless quantum simulations. To determine the range of nonlinearities that the algorithm can process for other IVPs, we study several PDEs, first beginning with the Navier-Stokes equations and progressing to other equations underlying physical phenomena ranging from electromagnetism, gravitation, and shallow wave propagation, from simulations of the Einstein, Boussniesq-type, Lin-Tsien, Camsssa-Holm, Drinfeld-Sokolov-Wilson (DSW), Hunter-Saxton, and Benney-Luke equations. To formulate optimization routines that the VQA undergoes to obtain numerical approximations of solutions that are abstracted from quantum circuit readout, cost functions corresponding to each PDE are provided in the supplementary section after which simulations results from hundreds of ZGR-QFT ansatzae are generated. With such an ensemble of ansatzae that we perform numerical experiments upon through time-evolution of quantum states corresponding to solution approximations of a PDE, we can readily compare different initial states of the solution across different PDEs that the VQA can effectively approximate, and establish various comparisons between computational complexity of optimizing different cost functions. To quantify VQA performance for approximating solutions to many PDEs, we perform our quantum circuit implementation with the open source Cirq platform, which prepares, and updates, the state vector corresponding to a PDE solution throughout the time evolution. To determine whether barren plateaus when optimizing for the ground state can be avoided, we also execute gradient-based, and stochastic, optimization procedures, which are compared with the performance of deterministic optimizers on a case-by-case basis.