---
title: "Effective Wages under Workforce Scheduling with Heterogeneous Time Preferences"
---
**Speaker:** [Raghav Singal](https://www.tuck.dartmouth.edu/faculty/faculty-directory/raghav-singal) (Dartmouth, Tuck)

**Date:** 6/6/23

**Abstract:** Problem definition: Motivated by the debate around drivers' welfare in on-demand transportation, we propose a framework to evaluate current practices and also possible alternatives. We study a setting in which riders seek drivers and a platform facilitates such matches over the course of the day. The platform allocates time slots to drivers using an allocation policy, and the drivers are strategic agents who maximize expected utility that depends on their preferred times to be on road, the allocated slots and the total on-road time. On the one hand, the platform seeks to ensure that a sufficient number of drivers is available to satisfy demand, and on the other hand, drivers aim to maximize their utility, which is driven by wages.  Methodology / results: Our framework evaluates policies on two dimensions: the supply of drivers across the day, and the effective wages of drivers. We illustrate that several families of policies have serious limitations both in terms of driver supply and effective wages. We find these limitations exist because the policies do not let drivers fully express their preferences and/or cannot account for heterogeneity in drivers' preferences. We propose a new allocation policy and establish strong performance guarantees with respect to both driver supply and effective wages. The policy is simple and fully leverages the market information to reach better market outcomes. We supplement our theory with numerical experiments calibrated on various New York City datasets that illustrate performance across a range of markets. Managerial implications: The paper highlights a possible fundamental inefficiency of policies deployed that limit driver's ability to express their preferences. By allowing drivers to express their temporal preferences, and using the priority-based allocation policy we devise to accommodate heterogeneity in such preferences, it is possible to obtain a potentially significant Pareto improvement, maintaining (or even increasing) driver supply while also increasing drivers' effective wages. Working paper available at https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4202484.