---
title: "Energy conservative quadrature based hyperreduction of Lagrangian hydrodynamics problems"
---
**Speaker:** Chris Vales (UNH)

**Date:** 3/5/24

**Abstract:** Dimension reduction methods are used to approximate the numerical discretization of a model in order to reduce the computational cost of its simulation while staying faithful to the full dynamics. To achieve this, projection-based methods construct a reduced basis from full simulation data and project the dynamics onto the spanned linear subspace. For nonlinear problems, hyper-reduction methods are additionally needed to remove the dependence of the nonlinear terms on the full problem’s size, completing the reduction process. In this work, we develop an energy conservative hyperreduction method for hydrodynamics PDE problems discretized on a Lagrangian moving grid by high order finite element methods. Based on an existing empirical quadrature procedure, our method employs sparse numerical quadrature rules to estimate the model’s nonlinear integral terms with a chosen degree of accuracy while ensuring that energy is conserved. We apply our method to well established benchmark problems, demonstrating that it achieves superior energy conservation and similar accuracy and computational speedup compared to the preexisting, non-conservative method.