---
title: "Dynamics of coupled Arctic air-ice-ocean interactions from floe scale to basin scale"
---
**Speaker:** [Daniel Watkins](https://danielmwatkins.com/) (Brown)

**Date:** 10/10/23

**Abstract:** Sea ice is a defining component of the coupled Arctic air-ice-ocean system. Sea ice mediates the exchange of momentum, heat, and moisture between the atmosphere and the ocean and is therefore a critical component for Earth system modeling, including climate prediction and weather forecasting. Ice motion results from the complex interaction of stresses from the winds and ocean currents, gravity, and Earth’s rotation. The motion and deformation of the ice resulting from these interacting stresses depends on the spatially and temporally varying ice strength, and on the orientation of the stresses relative to coastal features and the ice-ocean boundary. The compounded effects of small forces across large areas results in shearing, cracking, and opening of the ice surface. Many sea ice properties exhibit power law relationships across spatial and temporal scales. In this talk, I’ll present recent results on air-ice-ocean dynamics based on two complementary types of observations: in situ measurements from buoys and autonomous weather stations deployed during the Multidisciplinary drifting Observatory for the Study of Arctic Climate (MOSAiC), and remote sensing observations from satellite imagery via the Ice Floe Tracker (IFT) algorithm. Our results highlight the multiscale nature of sea ice motion. The MOSAiC buoys were deployed in a nested array allowing measurement of differential ice motion at hourly timescales. From these measurements, we show that abrupt changes in ice dynamics are associated with transitions in ocean seafloor topography. Topographic effects are particularly strong in tidal and inertial frequency bands, producing effects on ice deformation at daily and twice daily timescales at spatial scales of a few kilometers. Additionally, current jets at shelf boundaries align with high ice drift speeds, likely contributing to enhanced shear in the ice. Analysis of the IFT floe trajectories over the last 20 years shows sharp gradients in the fraction of the drift attributable to wind forcing over the Greenland continental shelf, suggesting that accurate representation of ocean currents is critical for modeling and forecasting ice drift in the region. Finally, I will present new measurements of power law behavior in ice dynamics, including the importance of accounting for seasonality in describing ice properties.